shyambhat/InstagramKit

InstagramKit.podspec

https://github.com/shyambhat/InstagramKit/issues/75

Updated podspec to add resource - InstagramKit.plist

---

InstagramKit/Engine/InstagramEngine.h
InstagramKit/Models/IKUserInPhoto.h
InstagramKit/Models/InstagramMedia.h

Title says it all. Fixes issue #67.

Added missing includes. IK now compiles with Swift.

---

InstagramKit/Engine/InstagramEngine.h
InstagramKit/Engine/InstagramEngine.m

This makes it a little easier to grab the current authenticated user's posts.

Endpoints for users posted media.

---

InstagramKit/Models/InstagramMedia.h
InstagramKit/Models/InstagramMedia.m
InstagramKit/Models/InstagramModel.h

I've added a BOOL property to the InstagramMedia model to check if the logged in user has liked the respective media. Tested and works with or without an access token.

Added userHasLiked property to InstagramMedia.

---

README.md

I thought it would be helpful for newcomers to get a better idea of how to use InstagramKit. I know the sample project has code that can be experimented with but I think a little explanation would help people get their code up and running a bit faster.

README updated with extra usage instructions

---

InstagramKitDemo/InstagramKitDemo/Base.lproj/Main.storyboard
InstagramKitDemo/InstagramKitDemo/Classes/View/IKCollectionViewController.m
InstagramKitDemo/InstagramKitDemo/Classes/View/IKMediaViewController.m
InstagramKitDemo/InstagramKitDemo/InstagramKitDemo-Info.plist

The demo application runs now on native resolution on iPhone 6 / 6+.
I have included also some fixes which ensure that the layouts adapt properly to the bigger displays.

Resolution optimisation of InstagramKitDemo application for iPhone 6 / 6+

---

InstagramKit/Engine/InstagramEngine.h
InstagramKit/Engine/InstagramEngine.m
InstagramKit/Models/InstagramUser.m
InstagramKitDemo/InstagramKitDemo.xcodeproj/project.pbxproj
InstagramKitDemo/InstagramKitDemo/Classes/View/IKCollectionViewController.m
InstagramKitDemo/InstagramKitDemo/Classes/View/IKMediaViewController.m
InstagramKitDemo/Podfile

Removed server response parameter from success callbacks

Pr/105 Modifications to pr #105

---

InstagramKit/Models/InstagramModel.h

adding extern keyword to the variables

---

InstagramKit/Engine/InstagramEngine.h
InstagramKit/Engine/InstagramEngine.m
InstagramKit/Models/InstagramMedia.h
InstagramKit/Models/InstagramMedia.m
README.md

Changes:
- Added support for distance parameter in media/search query
- Added support for accessing location id value in media search results
I've been using this really useful library in my [Pixagogo](http://www.pixagogoapp.com), so wanted to share my fairly minor updates with everyone
Thanks
John Pollard

Added support for additional location searches

---

InstagramKit-Example/InstagramKit-Example/Classes/View/IKLoginViewController.m
InstagramKit/Engine/InstagramEngine.h
InstagramKit/Engine/InstagramEngine.m
InstagramKitTests/Categories/InstagramEngine+Internal.h
README.md

find "authorizarion" and replace with "authorization".

fixed typo on lexical "authorization"

---

InstagramKit/Engine/InstagramEngine.h
InstagramKit/Engine/InstagramEngine.m
InstagramKit/Models/InstagramMedia.h
InstagramKit/Models/InstagramMedia.m

#149 Removed older API method getMediaAtLocation: without the distance

---

InstagramKit/Engine/InstagramEngine.m

fix percent-encoding in a pagination.

fix pagination. avoid percent-encoding twice.

---

.travis.yml
InstagramKit/Engine/InstagramEngine.h
InstagramKit/InstagramKitConstants.h
InstagramKit/Models/InstagramComment.h
InstagramKit/Models/InstagramLocation.h
InstagramKit/Models/InstagramMedia.h
InstagramKit/Models/InstagramModel.h
InstagramKit/Models/InstagramPaginationInfo.h
InstagramKit/Models/InstagramTag.h
InstagramKit/Models/InstagramUser.h

This makes the framework much nicer for use in Swift. Not sure if error in the failure block type should be nullable.

Add Nullability and Lightweight Generics for Xcode 7

---

InstagramKit-Example/InstagramKit-Example.xcodeproj/xcshareddata/xcschemes/InstagramKit-Example.xcscheme
InstagramKit-Example/InstagramKit-Example/Base.lproj/Main.storyboard
InstagramKit.xcodeproj/project.pbxproj
InstagramKit.xcodeproj/xcshareddata/xcschemes/InstagramKit.xcscheme
InstagramKit.xcodeproj/xcshareddata/xcschemes/InstagramKitTests.xcscheme
InstagramKit/Engine/InstagramEngine.h
InstagramKit/Engine/InstagramEngine.m
InstagramKit/InstagramKitConstants.h
InstagramKit/InstagramKitConstants.m
InstagramKit/Models/InstagramComment.h
InstagramKit/Models/InstagramComment.m
InstagramKit/Models/InstagramLocation.h
InstagramKit/Models/InstagramLocation.m
InstagramKit/Models/InstagramMedia.h
InstagramKit/Models/InstagramMedia.m
InstagramKit/Models/InstagramModel.h
InstagramKit/Models/InstagramModel.m
InstagramKit/Models/InstagramPaginationInfo.h
InstagramKit/Models/InstagramPaginationInfo.m
InstagramKit/Models/InstagramTag.h
InstagramKit/Models/InstagramTag.m
InstagramKit/Models/InstagramUser.h
InstagramKit/Models/InstagramUser.m
InstagramKitTests/Info.plist
InstagramKitTests/InstagramEngineBaseTests.m
InstagramKitTests/InstagramEngineMediaTests.m
InstagramKitTests/InstagramEngineUserTests.m
InstagramKitTests/InstagramKitTestsConstants.h

- Correcting nullability specifiers
- Improving really old model classes code.
- Unit Tests

Refactoring

---

InstagramKit/Engine/InstagramEngine.m
InstagramKit/InstagramKitConstants.h

@shyambhat tiny modify to adapt the new Instagram Permission, please check & merge it, thanks.

solve issue #194: New Permissions For Instagram

---

InstagramKit/Engine/InstagramEngine.h
InstagramKit/Engine/InstagramEngine.m
InstagramKitTests/Categories/InstagramEngine+Internal.h
InstagramKitTests/InstagramEngineBaseTests.m

This addresses https://github.com/shyambhat/InstagramKit/issues/131

Added support for app:// formatted custom redirect url.

---

InstagramKit/Engine/InstagramEngine.h
InstagramKit/Models/InstagramMedia.m

Hi,  I'd like to compile InstagramKit for Mac.  Here's a few changes that are needed to get it to compile. Thanks

Fixes to compile on Mac target

---

README.md

Currently since iOS 8, the recommended WebView component to use is WKWebView. I added an example to the README, how to use that.

Add WKWebView variant to the README.md

---

README.md

change wrong names

---

InstagramKit/Engine/InstagramEngine.m

only delete cookies for instagram.com in -[InstagramEngine logout]

---

Podfile

Every new person who clones your repo will have to make this change to install AFNetworking...
Thought I'd add this small addition 👍

Added Required Target to Podfile

---

InstagramKit/Engine/InstagramEngine.m

This fixes a possible null dereference if error is passed in as NULL

Fix a possible null dereference
